POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "Greyson Kihn",
"number": "171-2772566"
}

###

POST https://tranquil-beyond-01288.herokuapp.com/api/persons
Content-Type: application/json

{
"name": "Greyson Kihn",
"number": "171-2772566"
}